[[filters]]
"rdf:type" = "gndo:CorporateBody"

[[filters]]
"rdf:type" = "gndo:Company"

[[filters]]
"rdf:type" = "gndo:FictiveCorporateBody"

[[filters]]
"rdf:type" = "gndo:MusicalCorporateBody"

[[filters]]
"rdf:type" = "gndo:OrganOfCorporateBody"

[[filters]]
"rdf:type" = "gndo:ProjectOrProgram"

[[filters]]
"rdf:type" = "gndo:ReligiousAdministrativeUnit"

[[filters]]
"rdf:type" = "gndo:ReligiousCorporateBody"


[attributes]
label = ["gndo:preferredNameForTheCorporateBody", "gndo:variantNameForTheCorporateBody"]
start_date = "gndo:dateOfEstablishment"
end_date = "gndo:dateOfTermination"
sameas = "owl:sameAs"
