{% block filters %}
[[filters]]
"wdt:P31" = "wd:Q414147"
{% endblock filters %}

{% block attributes %}
[attributes]
label = ["schema:about/rdfs:label", "rdfs:label"]
same_as = ["owl:sameAs", "wdtn:P227", "wdtn:P1566", "wdtn:P214", "wdtn:P244"]
{% endblock attributes %}
