{% block filters %}
[[filters]]
"rdf:type" = "gndo:CorporateBody"

[[filters]]
"rdf:type" = "gndo:Company"

[[filters]]
"rdf:type" = "gndo:FictiveCorporateBody"

[[filters]]
"rdf:type" = "gndo:MusicalCorporateBody"

[[filters]]
"rdf:type" = "gndo:OrganOfCorporateBody"

[[filters]]
"rdf:type" = "gndo:ProjectOrProgram"

[[filters]]
"rdf:type" = "gndo:ReligiousAdministrativeUnit"

[[filters]]
"rdf:type" = "gndo:ReligiousCorporateBody"
{% endblock filters %}

{% block attributes %}
[attributes]
label = ["gndo:preferredNameForTheCorporateBody", "gndo:variantNameForTheCorporateBody"]
start_date = "gndo:dateOfEstablishment"
end_date = "gndo:dateOfTermination"
sameas = "owl:sameAs"
{% endblock attributes %}
